name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: Enable pnpm (corepack)
      run: corepack enable
      shell: bash

    - name: Cache pnpm store
      id: pnpm-store-cache
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: |
        pnpm install --frozen-lockfile
        pnpm --dir example install --no-frozen-lockfile
      shell: bash
