name: Setup
description: Setup Node.js and install dependencies
inputs:
  REACT_NATIVE_VERSION:
    description: React Native version to use
    required: false
  NODE_VERSION:
    description: Node version to use # https://github.com/actions/setup-node#supported-version-syntax
    required: false
  IS_EXPO:
    description: Should template use expo
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}

    - name: Display current inputs
      run: echo REACT_NATIVE_VERSION $REACT_NATIVE_VERSION & echo NODE_VERSION $NODE_VERSION & echo IS_EXPO $IS_EXPO
      shell: bash
      env:
        REACT_NATIVE_VERSION: ${{ inputs.REACT_NATIVE_VERSION }}
        NODE_VERSION: ${{ inputs.NODE_VERSION }}
        IS_EXPO: ${{ inputs.IS_EXPO }}

    - name: Enable pnpm (corepack)
      run: corepack enable
      shell: bash

    - name: Cache pnpm store
      id: pnpm-store-cache
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ inputs.REACT_NATIVE_VERSION }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.REACT_NATIVE_VERSION }}-pnpm-store-

    - name: Install dependencies
      run: |
        pnpm install --frozen-lockfile
        pnpm --dir example install --no-frozen-lockfile
        if [[ "$IS_EXPO" == "true" ]]; then
          pnpm --dir example-expo install --no-frozen-lockfile
        fi
      shell: bash
      env:
        IS_EXPO: ${{ inputs.IS_EXPO }}
