// __tests__/PackageArtifactHonesty.test.js

const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const packageJson = require('../package.json')
const buildScript = path.join(root, 'scripts', 'ci', 'build-package.js')
const artifactVerifier = path.join(root, 'scripts', 'ci', 'verify-package-artifacts.js')
const tarballVerifier = path.join(root, 'scripts', 'ci', 'verify-package-tarballs.js')

describe('package artifact honesty gate', () => {
  test('build and prepack verify the current published artifact surface', () => {
    expect(packageJson.scripts.build).toBe('pnpm prepack')
    expect(packageJson.scripts.lint).toContain('--max-warnings 0')
    expect(packageJson.scripts.prepack).toContain('build-package.js')
    expect(fs.existsSync(buildScript)).toBe(true)
    expect(fs.existsSync(artifactVerifier)).toBe(true)
    expect(fs.existsSync(tarballVerifier)).toBe(true)
    const buildSource = fs.readFileSync(buildScript, 'utf8')
    const verifierSource = fs.readFileSync(artifactVerifier, 'utf8')
    const tarballVerifierSource = fs.readFileSync(tarballVerifier, 'utf8')
    const shimPackSource = fs.readFileSync(path.join(root, 'scripts', 'prepare-shim-pack.js'), 'utf8')
    const packInstallSmokeSource = fs.readFileSync(path.join(root, 'scripts', 'ci', 'pack-install-smoke.js'), 'utf8')
    expect(buildSource).toContain("['run', 'clean:plugin']")
    expect(buildSource).toContain("['run', 'build:plugin']")
    expect(verifierSource).toContain('config-plugin artifact')
    expect(verifierSource).toContain('pluginOutputRoot')
    expect(verifierSource).toContain('internalTypeOnlySourceFiles')
    expect(verifierSource).toContain('internalRuntimeSourceFiles')
    expect(verifierSource).toContain('NativeUnifiedBleProtocolControl.ts')
    expect(verifierSource).toContain('native-protocol/rn-apple-boundary.ts')
    expect(verifierSource).toContain('native-protocol/rn-android-boundary.ts')
    expect(tarballVerifierSource).toContain('internalTypeOnlySourceFiles')
    expect(tarballVerifierSource).toContain('internalRuntimeSourceFiles')
    expect(tarballVerifierSource).toContain('expectedCodegenSourceEntries')
    expect(tarballVerifierSource).toContain('Packed React Native Codegen source set differs')
    expect(tarballVerifierSource).toContain('canonicalDependency !== canonicalVersion')
    expect(shimPackSource).toContain("process.platform === 'win32' ? 'npm.cmd' : 'npm'")
    expect(shimPackSource).toContain('--pack-destination')
    expect(packInstallSmokeSource).toContain("process.platform === 'win32' ? 'npm.cmd' : 'npm'")
    expect(packInstallSmokeSource).toContain('--pack-destination')
    expect(packInstallSmokeSource).not.toContain('cleanupRootTarballs')
    expect(packInstallSmokeSource).toContain("moduleResolution: 'Bundler'")
    expect(packInstallSmokeSource).toContain("moduleResolution: 'Node16'")
    expect(packInstallSmokeSource).toContain("moduleResolution: 'NodeNext'")
    expect(packInstallSmokeSource).toContain('unified-ble-manager/backend-sdk')
    expect(packInstallSmokeSource).toContain('unified-ble-manager/testing')
    expect(packInstallSmokeSource).toContain('unified-ble-manager/react-native')
    expect(packInstallSmokeSource).toContain('unified-ble-manager/cli')
    expect(packInstallSmokeSource).toContain("'ubm'")
    expect(packInstallSmokeSource).toContain('writeExternalCliBackendFixture')
    expect(packInstallSmokeSource).toContain('./external-deterministic-backend.cjs')
    expect(packInstallSmokeSource).toContain('identity.valid-all-axis-negotiation')
    expect(packInstallSmokeSource).toContain('@sfourdrinier/react-native-ble-plx')
    expect(packInstallSmokeSource).toContain("require('unified-ble-manager/app.plugin.js')")
    expect(packInstallSmokeSource).toContain("require('@sfourdrinier/react-native-ble-plx/app.plugin.js')")
    expect(packInstallSmokeSource).toContain(
      "assert.strictEqual(shimPlugin, canonicalPlugin, 'shim app.plugin.js resolves the canonical plugin instance')"
    )
    expect(packInstallSmokeSource).toContain("await import('@sfourdrinier/react-native-ble-plx')")
    expect(packInstallSmokeSource).toContain("require('unified-ble-manager/web')")
    expect(packInstallSmokeSource).toContain('ERR_PACKAGE_PATH_NOT_EXPORTED')
    expect(packInstallSmokeSource).toContain('unified-ble-manager/native-protocol/v1-codec')
    expect(packInstallSmokeSource).toContain('unified-ble-manager/native-protocol/rn-apple-boundary')
    expect(packInstallSmokeSource).toContain("await import('unified-ble-manager/web')")
    expect(packInstallSmokeSource).toContain(
      "import { createNavigatorWebBluetoothProvider } from 'unified-ble-manager/web'"
    )
    expect(tarballVerifierSource).toContain('isRootArchiveEntryAllowed')
    expect(tarballVerifierSource).toContain('assertExactShimArchiveEntries')
    expect(tarballVerifierSource).toContain('assertExactShimManifest')
    expect(tarballVerifierSource).toContain('docs/evidence/g0')
    expect(packageJson.files).toContain('!docs/evidence/g0/**')
    expect(packageJson.files).toContain('bin')
    expect(packageJson.files).toContain('src')
    expect(packageJson.bin).toEqual({ ubm: 'bin/ubm.js' })
  })
})
